# DB Subchart
database:
  name: bgg-db
  mysqlport: 3306
  claimname: dbpvc
  storageprovisioner: dobs.csi.digitalocean.com
  accessmodes: ReadWriteOnce
  storagesize: 2Gi
  storageclass: do-block-storage
  replicaCount: 1
  image:
    repository: stackupiss/bgg-db
    tag: v1
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 3306

bggv1:
  name: bgg-app-1
  dbHost: bgg-db.workshop03.svc.cluster.local
  replicaCount: 2
  appPort: 3000
  image:
    repository: stackupiss/bgg-app
    tag: v1
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi


bggv2:
  name: bgg-app-2
  dbHost: bgg-db.workshop03.svc.cluster.local
  replicaCount: 2
  appPort: 3000
  image:
    repository: stackupiss/bgg-app
    tag: v2
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: “false”
  hosts: []
  #  - host: chart-example.local
  
  paths:
  - path: /v1
    backend:
      serviceName: bgg-app-v1
      servicePort: 80
  - path: /v2
    backend:
      serviceName: bgg-app-v2
      servicePort: 8080
  - path: /
    backend:
      serviceName: bgg-app-v2
      servicePort: 8080

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
