replicaCount: 2
appPort: 3000
dbHost: bgg-db-svc.workshop03.svc.cluster.local

image:
  repository: stackupiss/bgg-app
  tag: v2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
