---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bggchartv2.labels" . | indent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - name: mysql-port-svc
    port: {{ .Values.database.service.port }}
    targetPort: mysql-port
  selector:
    app.kubernetes.io/name: {{ include "bggchartv2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.bggv1.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bggchartv2.labels" . | indent 4 }}
spec:
  type: {{ .Values.bggv1.service.type }}
  ports:
    - port: {{ .Values.bggv1.service.port }}
      targetPort: bgg-app-port-v1
      name: bgg-app-svc-port-v1
  selector:
    app.kubernetes.io/name: {{ include "bggchartv2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.bggv2.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bggchartv2.labels" . | indent 4 }}
spec:
  type: {{ .Values.bggv2.service.type }}
  ports:
    - port: {{ .Values.bggv2.service.port }}
      targetPort: bgg-app-port-v2
      name: bgg-app-svc-port-v2
  selector:
    app.kubernetes.io/name: {{ include "bggchartv2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}